"""Private: real version-1 checkpoint bytes captured before the v2 bump.

Shared by the built-in self-checks and the unittest suite so v1 read
compatibility is exercised against genuine old-format files.
"""

from __future__ import annotations

import base64

_TRAINED_B64 = (
    "U0VRRUNLUDEBAAAA7AAAAAAAAAB7ImdyYWRzIjpbWzIsM10sWzMsM10sWzNdLFszLDJdLFsyLDJd"
    "LFsyXV0sImhpZGRlbiI6W1syLDNdLFsyLDJdXSwibGF5ZXJzIjpbeyJraW5kIjoiX1JOTlN0ZXAi"
    "LCJzaGFwZXMiOltbMiwzXSxbMywzXSxbM11dfSx7ImtpbmQiOiJfUk5OU3RlcCIsInNoYXBlcyI6"
    "W1szLDJdLFsyLDJdLFsyXV19XSwicGFyYW1zIjpbWzIsM10sWzMsM10sWzNdLFszLDJdLFsyLDJd"
    "LFsyXV0sInBlbmRpbmciOmZhbHNlLCJ2IjoxfWaamZmZmZm5P2aamZmZmZnJv2YzMzMzMzPTP2aa"
    "mZmZmZnZP2aamZmZmZmpP2aamZmZmZm5v2aamZmZmZnJP2aamZmZmZm5v2YAAAAAAAAAAGaamZmZ"
    "mZm5P2YzMzMzMzPTP2aamZmZmZnJv2YzMzMzMzPTv2aamZmZmZm5P2aamZmZmZnJP2Z7FK5H4XqE"
    "P2Z7FK5H4XqUv2a4HoXrUbieP2aamZmZmZnJP2YzMzMzMzPTv2aamZmZmZm5P2aamZmZmZnZP2aa"
    "mZmZmZnJv2aamZmZmZm5P2YzMzMzMzPTP2aamZmZmZm5v2aamZmZmZnJP2aamZmZmZnJP2Z7FK5H"
    "4XqEv2Z7FK5H4XqUP2bvT9Ex3zh4P2bRY9S5Oj+ev2bDBt+a9JZ3P2au9sXV+mNwP2bVhNDvx5yY"
    "v2YyFy/Llix0P2YAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYA"
    "AAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGbPfa5jObCSP2bGb4szF0u4v2ZIWEXJ"
    "GyyTP2ZrOZ2/Uqmav2aOf/eclYuav2bKDPYzTj+LP2Zq8IHPAmCLP2aSCAu+gwuTv2ZFK7q4HCaT"
    "v2YAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGZkggo32HzIv2bze2zHD4PIv2YO"
    "h/LoFXikv2b+FGNhh9zAv2Z//qwt5eDJP2YhYH8M+PPTP2Zvng8sLLh+v2Z+ng8sLLh+v2YUhxEC"
    "oUyyv2YDZaCN3II/v2a4YP4YzCmrP2YgWjo8ir6zv1NFUUVDS1AxRU5ERgAAAAAAAABwzXCi"
)
_TRICKY_B64 = (
    "U0VRRUNLUDEBAAAA4wAAAAAAAAB7ImdyYWRzIjpbWzIsM10sWzMsM10sWzNdLFszLDJdLFsyLDJd"
    "LFsyXV0sImhpZGRlbiI6bnVsbCwibGF5ZXJzIjpbeyJraW5kIjoiX1JOTlN0ZXAiLCJzaGFwZXMi"
    "OltbMiwzXSxbMywzXSxbM11dfSx7ImtpbmQiOiJfUk5OU3RlcCIsInNoYXBlcyI6W1szLDJdLFsy"
    "LDJdLFsyXV19XSwicGFyYW1zIjpbWzIsM10sWzMsM10sWzNdLFszLDJdLFsyLDJdLFsyXV0sInBl"
    "bmRpbmciOmZhbHNlLCJ2IjoxfWYAAAAAAAD4P2YAAAAAAAAAgGYAAAAAAAAKQGYAAJAexLzWQmYA"
    "AAAAAAAEwGYAAAAAAACwP2aamZmZmZnJP2aamZmZmZm5v2YAAAAAAAAAAGaamZmZmZm5P2YzMzMz"
    "MzPTP2aamZmZmZnJv2YzMzMzMzPTv2aamZmZmZm5P2aamZmZmZnJP2Z7FK5H4XqEP2Z7FK5H4XqU"
    "v2a4HoXrUbieP2aamZmZmZnJP2YzMzMzMzPTv2aamZmZmZm5P2aamZmZmZnZP2aamZmZmZnJv2aa"
    "mZmZmZm5P2YzMzMzMzPTP2aamZmZmZm5v2aamZmZmZnJP2aamZmZmZnJP2Z7FK5H4XqEv2Z7FK5H"
    "4XqUP2YAAAAAAAAAgGYAAAAAAAAAQGYAAAAAAAAIwGYAAAAAAAAAAGYAAAAAAADwP2YAAAAAAADw"
    "v2YAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYA"
    "AAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAA"
    "AAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAA"
    "AGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAGYAAAAAAAAAAFNFUUVDS1AxRU5E"
    "PAAAAAAAAAB6Mzjk"
)


def trained_bytes():
    return base64.b64decode(_TRAINED_B64)


def tricky_bytes():
    return base64.b64decode(_TRICKY_B64)
